services:
  crypto-pipeline:
    build: .
    container_name: crypto_tracker_container
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN} 
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: always
    
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: crypto_dashboard
    env_file:                               
      - .env                                
    environment:                            
      - PYTHONUNBUFFERED=1                  
      - DATABASE_URL=${DATABASE_URL}        
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    depends_on:
      - crypto-pipeline